# Generated by Django 2.0.7 on 2018-07-23 08:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='uploads')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('name', models.CharField(max_length=30, verbose_name='Название товара')),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
        ),
    ]
